# Generated by Django 5.1.4 on 2025-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proile',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
