# Generated by Django 5.1.4 on 2025-01-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_user_proile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proile',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
