# Generated by Django 5.1.4 on 2025-01-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_user_proile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='proile',
            new_name='profile',
        ),
    ]
