# Generated by Django 5.1.4 on 2025-01-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_rename_proile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default='buyer', max_length=20),
        ),
    ]
