# Generated by Django 5.1.4 on 2025-01-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('product', models.ManyToManyField(blank=True, to='myapp1.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp1.user')),
            ],
        ),
    ]
